from ..operators import (
    MVLT_OT_add_opacity_key,
    MVLT_OT_add_primary_keys,
    MVLT_OT_add_transform_keys,
    MVLT_OT_apply_fade_in,
    MVLT_OT_apply_fade_out,
    MVLT_OT_apply_shake,
    MVLT_OT_apply_zoom,
    MVLT_OT_assign_group,
    MVLT_OT_delete_layer,
    MVLT_OT_duplicate_layer,
    MVLT_OT_start_external_api_server,
    MVLT_OT_stop_external_api_server,
    MVLT_OT_import_images,
    MVLT_OT_import_sequence,
    MVLT_OT_init_camera,
    MVLT_OT_initialize_scene,
    MVLT_MT_topbar_menu,
    MVLT_OT_open_effects_window,
    MVLT_OT_open_import_window,
    MVLT_OT_open_layer_timeline_editor,
    MVLT_OT_open_layers_window,
    MVLT_OT_open_scene_window,
    MVLT_OT_open_timeline_window,
    MVLT_OT_refresh_layers,
    MVLT_OT_register_selected_as_layer,
    MVLT_OT_reorder_layer,
    MVLT_OT_select_layer,
    MVLT_OT_start_direct_edit_mode,
    MVLT_OT_stop_direct_edit_mode,
    MVLT_OT_set_frame_range,
    MVLT_OT_set_opacity,
    MVLT_OT_toggle_lock,
    MVLT_OT_toggle_visibility,
    MVLT_OT_jump_to_layer_end,
    MVLT_OT_jump_to_layer_start,
    MVLT_OT_nudge_frame,
    MVLT_OT_set_layer_in_from_current,
    MVLT_OT_set_layer_out_from_current,
)
from ..properties.effect_props import MVLT_EffectSettings
from ..properties.import_props import MVLT_ImportSettings
from ..properties.layer_props import MVLT_LayerSettings
from ..properties.scene_props import MVLT_SceneSettings
from ..properties.ui_state_props import MVLT_LayerListItem, MVLT_UIState
from ..viewport import MVLT_OT_direct_edit_modal
from ..ui import (
    MVLT_PT_effects_panel,
    MVLT_PT_import_panel,
    MVLT_PT_layers_panel,
    MVLT_PT_scene_tools_panel,
    MVLT_PT_tabs,
    MVLT_PT_timeline_panel,
    MVLT_UL_layer_list,
)


CLASSES = [
    MVLT_SceneSettings,
    MVLT_LayerListItem,
    MVLT_UIState,
    MVLT_ImportSettings,
    MVLT_EffectSettings,
    MVLT_LayerSettings,
    MVLT_OT_import_images,
    MVLT_OT_import_sequence,
    MVLT_OT_register_selected_as_layer,
    MVLT_OT_delete_layer,
    MVLT_OT_duplicate_layer,
    MVLT_OT_start_external_api_server,
    MVLT_OT_stop_external_api_server,
    MVLT_OT_reorder_layer,
    MVLT_OT_select_layer,
    MVLT_OT_toggle_visibility,
    MVLT_OT_toggle_lock,
    MVLT_OT_set_frame_range,
    MVLT_OT_jump_to_layer_start,
    MVLT_OT_jump_to_layer_end,
    MVLT_OT_nudge_frame,
    MVLT_OT_set_layer_in_from_current,
    MVLT_OT_set_layer_out_from_current,
    MVLT_OT_add_primary_keys,
    MVLT_OT_add_transform_keys,
    MVLT_OT_add_opacity_key,
    MVLT_OT_apply_fade_in,
    MVLT_OT_apply_fade_out,
    MVLT_OT_apply_shake,
    MVLT_OT_apply_zoom,
    MVLT_OT_set_opacity,
    MVLT_OT_open_import_window,
    MVLT_OT_open_layer_timeline_editor,
    MVLT_OT_open_layers_window,
    MVLT_OT_open_timeline_window,
    MVLT_OT_open_effects_window,
    MVLT_OT_open_scene_window,
    MVLT_OT_init_camera,
    MVLT_OT_assign_group,
    MVLT_OT_initialize_scene,
    MVLT_OT_refresh_layers,
    MVLT_OT_start_direct_edit_mode,
    MVLT_OT_stop_direct_edit_mode,
    MVLT_OT_direct_edit_modal,
    MVLT_MT_topbar_menu,
    MVLT_UL_layer_list,
    MVLT_PT_tabs,
    MVLT_PT_import_panel,
    MVLT_PT_layers_panel,
    MVLT_PT_timeline_panel,
    MVLT_PT_effects_panel,
    MVLT_PT_scene_tools_panel,
]

