ADDON_ID = "mv_layer_tools"
ADDON_PREFIX = "MVLT"
MASTER_COLLECTION_NAME = "MVLT_Master"
CAMERA_NAME = "MVLT_Camera"
PANEL_CATEGORY = "AVIUTL"

LAYER_TYPE_IMAGE = "IMAGE"
LAYER_TYPE_SEQUENCE = "SEQUENCE"
LAYER_TYPE_SOLID = "SOLID"

SOURCE_KIND_IMAGE = "IMAGE"
SOURCE_KIND_SEQUENCE = "SEQUENCE"

TAB_IMPORT = "IMPORT"
TAB_LAYERS = "LAYERS"
TAB_TIMELINE = "TIMELINE"
TAB_EFFECTS = "EFFECTS"
TAB_SCENE = "SCENE"
